version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --require-secure-transport=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_photos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./certs:/etc/mysql/certs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:

